[package]
name = "site_counter"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = "0.4.6"
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15"
colored = "3.0.0"
lazy_static = "1.5.0"
tempfile = "3.20.0"
dashmap = "6.1.0"
num-traits = "0.2.19"
